version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pg
    versions:
    - 1.2.3
  - dependency-name: uglifier
    versions:
    - 4.2.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
